 package game.parts;
 
import static org.lwjgl.input.Keyboard.*;

import game.GButton;
import game.GSprite;
import game.Game;
import game.GamePart;
import game.Main;
import game.Game.GState;
import static game.input.GKeyboard.*;


 
 import java.util.ArrayList;
 
import org.lwjgl.opengl.Display;

import controllers.Controlls;

public class InventoryMenu implements GamePart{
	GSprite Inventory = new GSprite(Display.getWidth()/2,Display.getHeight()/2, 600, 480, "UI/Inventory");



 	public void handleInput() {
		if(isKeyPressed(Controlls.INVENTORY_KEY)){
			Main.game.revertGameState();
			}

 		
 	}
 
	public void Inventory(int size) {
	
	}

 	@Override
 	public void update() {
 		// TODO Autogenerated method stub

		
 	}
 
	public void render() {
		Inventory.render();
	
		
 	}

/*	public void addItem(GItem go){
	
	public void addItem(GItem go){
 		for(int i = 0; i < slots.length; i){
 				if(slots[i] == null){
 					slots.;
 			}	
 		}
 	}

	public void addItem(GItem go, int i) {
(null)
	
	public void addItem(GItem go, int i){
(null)
 		slots[i] = go;
	}*/
	}

 
 